# Generated by Django 3.2.6 on 2021-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Name', models.CharField(default='', max_length=20)),
                ('Group_Type', models.CharField(default='', max_length=30)),
                ('Group_Representative_Name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MCE_CSE_Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='', max_length=50)),
                ('project_alloted', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MCE_Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(default='', max_length=10)),
                ('Mentor_Teacher', models.CharField(default='', max_length=50)),
                ('Group_Name', models.CharField(default='', max_length=20)),
                ('Group_Representative_Name', models.CharField(default='', max_length=50)),
                ('Group_Type', models.CharField(default='', max_length=10)),
                ('Member1_Name', models.CharField(default='', max_length=50)),
                ('Member1_Roll', models.IntegerField(default=False)),
                ('Member2_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member2_Roll', models.IntegerField(blank=True, null=True)),
                ('Member3_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member3_Roll', models.IntegerField(blank=True, null=True)),
                ('Member4_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member4_Roll', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCE_Student_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(default='', max_length=10)),
                ('Mentor_Teacher', models.CharField(default='', max_length=50)),
                ('Group_Name', models.CharField(default='', max_length=20)),
                ('Group_Representative_Name', models.CharField(default='', max_length=50)),
                ('Group_Type', models.CharField(default='', max_length=10)),
                ('Member1_Name', models.CharField(default='', max_length=50)),
                ('Member1_Roll', models.IntegerField(default=False)),
                ('Member2_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member2_Roll', models.IntegerField(blank=True, null=True)),
                ('Member3_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member3_Roll', models.IntegerField(blank=True, null=True)),
                ('Member4_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member4_Roll', models.IntegerField(blank=True, null=True)),
                ('Project_Name', models.CharField(default='', max_length=20)),
                ('Project_Abstract', models.TextField(default='')),
                ('Technologies_to_be_used', models.TextField(default='')),
                ('Project_Report', models.FileField(blank=True, null=True, upload_to='Project_Reports/')),
                ('Project_PPT', models.FileField(blank=True, null=True, upload_to='Project_PPTs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(default='', max_length=10)),
                ('Mentor_Teacher', models.CharField(default='', max_length=50)),
                ('Group_Name', models.CharField(default='', max_length=20)),
                ('Group_Representative_Name', models.CharField(default='', max_length=50)),
                ('Group_Type', models.CharField(default='', max_length=10)),
                ('Member1_Name', models.CharField(default='', max_length=50)),
                ('Member1_Roll', models.IntegerField(default=False)),
                ('Member2_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member2_Roll', models.IntegerField(blank=True, null=True)),
                ('Member3_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member3_Roll', models.IntegerField(blank=True, null=True)),
                ('Member4_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Member4_Roll', models.IntegerField(blank=True, null=True)),
                ('Project_Name', models.CharField(default='', max_length=20)),
                ('Project_Abstract', models.TextField(default='')),
                ('Technologies_to_be_used', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(default='', max_length=10),
        ),
    ]
