# Generated by Django 3.2.6 on 2021-11-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0002_auto_20211125_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetails',
            name='Group_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Group_Representative_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Group_Type',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member1_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member1_Roll',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member2_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member2_Roll',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member3_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member3_Roll',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member4_Name',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Member4_Roll',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Mentor_Teacher',
        ),
        migrations.RemoveField(
            model_name='reportdetails',
            name='Semester',
        ),
    ]
