# Generated by Django 3.2.6 on 2021-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0003_auto_20211125_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mce_student_details',
            name='Mentor_Teacher',
        ),
        migrations.RemoveField(
            model_name='mce_student_records',
            name='Mentor_Teacher',
        ),
        migrations.AddField(
            model_name='reportdetails',
            name='Group_Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportdetails',
            name='Mentor_Teacher',
            field=models.CharField(default='', max_length=50),
        ),
    ]
