# Generated by Django 3.2.7 on 2021-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0003_mce_cse_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCE_Student_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(default='', max_length=10)),
                ('Mentor_Teacher', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
