# Generated by Django 3.2.7 on 2021-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0004_mce_student_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='mce_student_records',
            name='Group_Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Group_Representative_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Group_Type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
