# Generated by Django 3.2.6 on 2021-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0004_auto_20211125_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='mce_student_records',
            name='Mentor_Teacher',
            field=models.CharField(default='', max_length=50),
        ),
    ]
