# Generated by Django 3.2.7 on 2021-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0005_auto_20210921_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='mce_student_records',
            name='Member1_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Member2_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Member3_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Member4_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Project_Abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Project_Name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Technologies_to_be_used',
            field=models.TextField(default=''),
        ),
    ]
