# Generated by Django 3.2.7 on 2021-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0006_auto_20210922_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mce_student_records',
            name='Project_Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
