# Generated by Django 3.2.7 on 2021-09-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0013_projectgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mce_cse_faculties',
            name='project_alloted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mce_cse_faculties',
            name='project_count',
            field=models.IntegerField(default=0),
        ),
    ]
