# Generated by Django 3.2.7 on 2021-10-01 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectMa_App', '0014_auto_20210929_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectGroup',
            new_name='Profile',
        ),
    ]
