# Generated by Django 3.2.7 on 2021-10-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0015_rename_projectgroup_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
