# Generated by Django 3.2.7 on 2021-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0017_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Name', models.CharField(default='', max_length=20)),
                ('Group_Type', models.CharField(default='', max_length=30)),
                ('Group_Representative_Name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Project_PPT',
            field=models.FileField(default=False, upload_to='Project_PPTs/'),
        ),
        migrations.AddField(
            model_name='mce_student_records',
            name='Project_Report',
            field=models.FileField(default=False, upload_to='Project_Reports/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
