# Generated by Django 3.2.7 on 2021-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0018_auto_20211005_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mce_student_records',
            name='Project_PPT',
            field=models.FileField(default='', upload_to='Project_PPTs/'),
        ),
        migrations.AlterField(
            model_name='mce_student_records',
            name='Project_Report',
            field=models.FileField(default='', upload_to='Project_Reports/'),
        ),
    ]
