# Generated by Django 3.2.7 on 2021-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMa_App', '0019_auto_20211007_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mce_student_records',
            name='Member2_Roll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mce_student_records',
            name='Member3_Roll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mce_student_records',
            name='Member4_Roll',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
